version: 2

jobs:
  build:
    working_directory: /home/timeago

    docker:
      - image: node:8

    steps:
      - checkout
      - run: npm i
      - run: npm test

    deployment:
      npm:
        tag: /v[0-9]+(\.[0-9]+)*/
        commands:
          - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          - run: npm publish