version: 2

jobs:
  build:
    working_directory: /home/timeago

    docker:
      - image: node:8

    steps:
      - checkout

      - run: npm i
      - run: npm test
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

      # # publish the build (if a tagged release)
      # - deploy:
      #     name: Publish to npm registry
      #     run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      #     run: npm publish